"""
Markdown report generator.

Produces a structured, human-readable .md report from a ScanSession.
The output format is intentionally plain — no exotic Markdown extensions,
compatible with GitHub, Obsidian, and most static site generators.
"""

from __future__ import annotations

import logging
from pathlib import Path

from models.results import ScanSession

logger = logging.getLogger(__name__)

_OUTPUT_DIR = Path("outputs")


def generate_markdown_report(
    session: ScanSession, output_dir: Path = _OUTPUT_DIR
) -> Path:
    """
    Render a full scan session as a Markdown document.

    Returns the path to the written file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    date_tag = session.started_at.strftime("%Y%m%d_%H%M%S")
    safe_target = _sanitise_filename(session.target)
    file_path = output_dir / f"{safe_target}_{date_tag}_report.md"

    content = _render(session)
    file_path.write_text(content, encoding="utf-8")

    logger.info("Markdown report written to %s", file_path)
    return file_path


def _render(session: ScanSession) -> str:
    sections = [
        _header(session),
        _summary_table(session),
        _subdomains_section(session),
        _ports_section(session),
        _http_section(session),
        _footer(session),
    ]
    return "\n\n".join(s for s in sections if s)


def _header(session: ScanSession) -> str:
    return (
        f"# Recon Report: {session.target}\n\n"
        f"**Target:** `{session.target}`  \n"
        f"**Started:** {session.started_at.strftime('%Y-%m-%d %H:%M:%S UTC')}  \n"
        f"**Finished:** "
        f"{session.finished_at.strftime('%Y-%m-%d %H:%M:%S UTC') if session.finished_at else 'N/A'}  \n"
        f"**Duration:** {session.duration_seconds or 0:.2f}s  \n"
        f"\n---"
    )


def _summary_table(session: ScanSession) -> str:
    open_ports = [p for p in session.ports if p.state == "open"]
    resolved_subdomains = [s for s in session.subdomains if s.resolved]

    return (
        "## Summary\n\n"
        "| Metric | Count |\n"
        "|---|---|\n"
        f"| Subdomains discovered | {len(session.subdomains)} |\n"
        f"| Subdomains resolved | {len(resolved_subdomains)} |\n"
        f"| Ports probed | {len(session.ports)} |\n"
        f"| Ports open | {len(open_ports)} |\n"
        f"| HTTP endpoints fingerprinted | {len(session.http_fingerprints)} |"
    )


def _subdomains_section(session: ScanSession) -> str:
    if not session.subdomains:
        return "## Subdomains\n\n_No subdomains discovered._"

    lines = [
        "## Subdomains\n",
        "| Subdomain | Source | Resolved | IP Address |",
        "|---|---|---|---|",
    ]
    for r in sorted(session.subdomains, key=lambda x: x.subdomain):
        resolved_flag = "Yes" if r.resolved else "No"
        ip = r.ip_address or "-"
        lines.append(f"| `{r.subdomain}` | {r.source} | {resolved_flag} | {ip} |")

    return "\n".join(lines)


def _ports_section(session: ScanSession) -> str:
    open_ports = [p for p in session.ports if p.state == "open"]

    if not open_ports:
        return "## Open Ports\n\n_No open ports found._"

    lines = [
        "## Open Ports\n",
        "| Port | Protocol | Service | Banner |",
        "|---|---|---|---|",
    ]
    for p in sorted(open_ports, key=lambda x: x.port):
        service = p.service or "-"
        banner = (p.banner[:80] + "…") if p.banner and len(p.banner) > 80 else (p.banner or "-")
        lines.append(f"| {p.port} | {p.protocol.upper()} | {service} | `{banner}` |")

    return "\n".join(lines)


def _http_section(session: ScanSession) -> str:
    if not session.http_fingerprints:
        return "## HTTP Fingerprints\n\n_No HTTP endpoints reachable._"

    blocks = ["## HTTP Fingerprints"]

    for fp in session.http_fingerprints:
        status_label = str(fp.status_code) if fp.status_code else "N/A"
        tech_label = ", ".join(fp.technologies) if fp.technologies else "-"
        redirect_label = f" → `{fp.redirect_url}`" if fp.redirect_url else ""

        block = (
            f"\n### {fp.url}\n\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| Status Code | {status_label}{redirect_label} |\n"
            f"| Server | {fp.server or '-'} |\n"
            f"| Content-Type | {fp.content_type or '-'} |\n"
            f"| X-Powered-By | {fp.x_powered_by or '-'} |\n"
            f"| Technologies | {tech_label} |\n"
            f"| Response Time | {fp.response_time_ms or '-'} ms |"
        )
        blocks.append(block)

    return "\n".join(blocks)


def _footer(session: ScanSession) -> str:
    return (
        "---\n\n"
        "_Generated by recon-engine. "
        "This report was produced during an authorized security assessment. "
        "Handle findings in accordance with your responsible disclosure policy._"
    )


def _sanitise_filename(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-._" else "_" for ch in name)[:64]
